export type { Icon, IconProps } from "./types"
export { TabletIcon } from "./lucide-tablet"
export { TabletIcon as Tablet } from "./lucide-tablet"
export { SmartphoneIcon } from "./lucide-smartphone"
export { SmartphoneIcon as Smartphone } from "./lucide-smartphone"
export { MousePointer2Icon } from "./lucide-mouse-pointer-2"
export { MousePointer2Icon as MousePointer2 } from "./lucide-mouse-pointer-2"
export { MonitorIcon } from "./lucide-monitor"
export { MonitorIcon as Monitor } from "./lucide-monitor"
export { Maximize2Icon } from "./lucide-maximize-2"
export { Maximize2Icon as Maximize2 } from "./lucide-maximize-2"
export { MaximizeIcon } from "./lucide-maximize"
export { MaximizeIcon as Maximize } from "./lucide-maximize"
export { BugIcon } from "./lucide-bug"
export { BugIcon as Bug } from "./lucide-bug"
export { ArrowLeftIcon } from "./lucide-arrow-left"
export { ArrowLeftIcon as ArrowLeft } from "./lucide-arrow-left"
export { FileBracesIcon } from "./lucide-file-braces"
export { FileBracesIcon as FileJson } from "./lucide-file-braces"
export { FileBracesIcon as FileBraces } from "./lucide-file-braces"
export { ListEndIcon } from "./lucide-list-end"
export { ListEndIcon as ListEnd } from "./lucide-list-end"
export { RefreshCwIcon } from "./lucide-refresh-cw"
export { RefreshCwIcon as RefreshCw } from "./lucide-refresh-cw"
export { PlayIcon } from "./lucide-play"
export { PlayIcon as Play } from "./lucide-play"
export { WebhookIcon } from "./lucide-webhook"
export { WebhookIcon as Webhook } from "./lucide-webhook"
export { ClockIcon } from "./lucide-clock"
export { ClockIcon as Clock } from "./lucide-clock"
export { Settings2Icon } from "./lucide-settings-2"
export { Settings2Icon as Settings2 } from "./lucide-settings-2"
export { ShieldCheckIcon } from "./lucide-shield-check"
export { ShieldCheckIcon as ShieldCheck } from "./lucide-shield-check"
export { GlobeIcon } from "./lucide-globe"
export { GlobeIcon as Globe } from "./lucide-globe"
export { BookOpenIcon } from "./lucide-book-open"
export { BookOpenIcon as BookOpen } from "./lucide-book-open"
export { DatabaseIcon } from "./lucide-database"
export { DatabaseIcon as Database } from "./lucide-database"
export { BoxesIcon } from "./lucide-boxes"
export { BoxesIcon as Boxes } from "./lucide-boxes"
export { PlugIcon } from "./lucide-plug"
export { PlugIcon as Plug } from "./lucide-plug"
export { Table2Icon } from "./lucide-table-2"
export { Table2Icon as Table2 } from "./lucide-table-2"
export { ArrowRightIcon } from "./lucide-arrow-right"
export { ArrowRightIcon as ArrowRight } from "./lucide-arrow-right"
export { ArrowDownIcon } from "./lucide-arrow-down"
export { ArrowDownIcon as ArrowDown } from "./lucide-arrow-down"
export { WorkflowIcon } from "./lucide-workflow"
export { WorkflowIcon as Workflow } from "./lucide-workflow"
export { SunIcon } from "./lucide-sun"
export { SunIcon as Sun } from "./lucide-sun"
export { Columns2Icon } from "./lucide-columns-2"
export { Columns2Icon as Columns2 } from "./lucide-columns-2"
export { FileTextIcon } from "./lucide-file-text"
export { FileTextIcon as FileText } from "./lucide-file-text"
export { FileImageIcon } from "./lucide-file-image"
export { FileImageIcon as FileImage } from "./lucide-file-image"
export { FileCode2Icon } from "./lucide-file-code"
export { FileCode2Icon as FileCode2 } from "./lucide-file-code"
export { FileCode2Icon as FileCode } from "./lucide-file-code"

export { GitForkIcon } from "./lucide-git-fork"
export { GitForkIcon as GitFork } from "./lucide-git-fork"
export { ArchiveIcon } from "./lucide-archive"
export { ArrowUpRightIcon } from "./lucide-arrow-up-right"
export { BotIcon } from "./lucide-bot"
export { BrainIcon } from "./lucide-brain"
export { CameraIcon } from "./lucide-camera"
export { CheckIcon } from "./lucide-check"
export { ChevronDownIcon } from "./lucide-chevron-down"
export { ChevronRightIcon } from "./lucide-chevron-right"
export { ChevronUpIcon } from "./lucide-chevron-up"
export { CircleCheckIcon } from "./lucide-circle-check"
export { CircleXIcon } from "./lucide-circle-x"
export { CodeXmlIcon } from "./lucide-code-xml"
export { CopyIcon } from "./lucide-copy"
export { EllipsisIcon } from "./lucide-ellipsis"
export { EraserIcon } from "./lucide-eraser"
export { EyeIcon } from "./lucide-eye"
export { FileIcon } from "./lucide-file"
export { FolderIcon } from "./lucide-folder"
export { FolderOpenIcon } from "./lucide-folder-open"
export { FolderTreeIcon } from "./lucide-folder-tree"
export { GaugeIcon } from "./lucide-gauge"
export { GitBranchIcon } from "./lucide-git-branch"
export { GitMergeIcon } from "./lucide-git-merge"
export { GitPullRequestIcon } from "./lucide-git-pull-request"
export { HistoryIcon } from "./lucide-history"
export { ImageIcon } from "./lucide-image"
export { InfoIcon } from "./lucide-info"
export { ListTodoIcon } from "./lucide-list-todo"
export { Loader2Icon } from "./lucide-loader-circle"
export { MessageCircleIcon } from "./lucide-message-circle"
export { MessagesSquareIcon } from "./lucide-messages-square"
export { MinusIcon } from "./lucide-minus"
export { MoonIcon } from "./lucide-moon"
export { NetworkIcon } from "./lucide-network"
export { OctagonXIcon } from "./lucide-octagon-x"
export { PanelLeftIcon } from "./lucide-panel-left"
export { PanelRightIcon } from "./lucide-panel-right"
export { PencilIcon } from "./lucide-pencil"
export { PlusIcon } from "./lucide-plus"
export { Redo2Icon } from "./lucide-redo-2"
export { RotateCwIcon } from "./lucide-rotate-cw"
export { SaveIcon } from "./lucide-save"
export { SearchIcon } from "./lucide-search"
export { SettingsIcon } from "./lucide-settings"
export { SlidersHorizontalIcon } from "./lucide-sliders-horizontal"
export { SparklesIcon } from "./lucide-sparkles"
export { SquarePenIcon } from "./lucide-square-pen"
export { Trash2Icon } from "./lucide-trash-2"
export { TriangleAlertIcon } from "./lucide-triangle-alert"
export { Undo2Icon } from "./lucide-undo-2"
export { XIcon } from "./lucide-x"

// Compat aliases for existing lucide-react import names
export { ArchiveIcon as Archive } from "./lucide-archive"
export { ArrowUpRightIcon as ArrowUpRight } from "./lucide-arrow-up-right"
export { BotIcon as Bot } from "./lucide-bot"
export { BrainIcon as Brain } from "./lucide-brain"
export { CameraIcon as Camera } from "./lucide-camera"
export { CheckIcon as Check } from "./lucide-check"
export { ChevronDownIcon as ChevronDown } from "./lucide-chevron-down"
export { ChevronRightIcon as ChevronRight } from "./lucide-chevron-right"
export { ChevronUpIcon as ChevronUp } from "./lucide-chevron-up"
export { CircleCheckIcon as CircleCheck } from "./lucide-circle-check"
export { CodeXmlIcon as Code2 } from "./lucide-code-xml"
export { CodeXmlIcon as CodeXml } from "./lucide-code-xml"
export { CopyIcon as Copy } from "./lucide-copy"
export { EllipsisIcon as Ellipsis } from "./lucide-ellipsis"
export { EllipsisIcon as MoreHorizontal } from "./lucide-ellipsis"
export { EraserIcon as Eraser } from "./lucide-eraser"
export { EyeIcon as Eye } from "./lucide-eye"
export { FileIcon as File } from "./lucide-file"
export { FolderIcon as Folder } from "./lucide-folder"
export { FolderOpenIcon as FolderOpen } from "./lucide-folder-open"
export { FolderTreeIcon as FolderTree } from "./lucide-folder-tree"
export { GaugeIcon as Gauge } from "./lucide-gauge"
export { GitBranchIcon as GitBranch } from "./lucide-git-branch"
export { GitMergeIcon as GitMerge } from "./lucide-git-merge"
export { GitPullRequestIcon as GitPullRequest } from "./lucide-git-pull-request"
export { HistoryIcon as History } from "./lucide-history"
export { ImageIcon as Image } from "./lucide-image"
export { InfoIcon as Info } from "./lucide-info"
export { ListTodoIcon as ListTodo } from "./lucide-list-todo"
export { Loader2Icon as Loader2 } from "./lucide-loader-circle"
export { Loader2Icon as LoaderCircle } from "./lucide-loader-circle"
export { MessageCircleIcon as MessageCircle } from "./lucide-message-circle"
export { MessagesSquareIcon as MessagesSquare } from "./lucide-messages-square"
export { MinusIcon as Minus } from "./lucide-minus"
export { MoonIcon as Moon } from "./lucide-moon"
export { NetworkIcon as Network } from "./lucide-network"
export { OctagonXIcon as OctagonX } from "./lucide-octagon-x"
export { PanelLeftIcon as PanelLeft } from "./lucide-panel-left"
export { PanelRightIcon as PanelRight } from "./lucide-panel-right"
export { PencilIcon as Pencil } from "./lucide-pencil"
export { PlusIcon as Plus } from "./lucide-plus"
export { Redo2Icon as Redo2 } from "./lucide-redo-2"
export { RotateCwIcon as RotateCw } from "./lucide-rotate-cw"
export { SaveIcon as Save } from "./lucide-save"
export { SearchIcon as Search } from "./lucide-search"
export { SettingsIcon as Settings } from "./lucide-settings"
export { SlidersHorizontalIcon as SlidersHorizontal } from "./lucide-sliders-horizontal"
export { SparklesIcon as Sparkles } from "./lucide-sparkles"
export { SquarePenIcon as SquarePen } from "./lucide-square-pen"
export { Trash2Icon as Trash2 } from "./lucide-trash-2"
export { TriangleAlertIcon as TriangleAlert } from "./lucide-triangle-alert"
export { Undo2Icon as Undo2 } from "./lucide-undo-2"
export { XIcon as X } from "./lucide-x"
export { CircleXIcon as XCircle } from "./lucide-circle-x"
export { CircleXIcon as CircleX } from "./lucide-circle-x"

